version: '3.8'

volumes:
  postgres_vol:

networks:
  postgres_network:
    driver: bridge

services:
  postgres_db: 
    container_name: postgres_db
    image: postgres:14.5
    networks:
      - postgres_network
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pwd_postgres

  pgadmin:
    container_name: pg4admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - postgres_network
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pwd